const PLAN_SCHEMA = {
  gratis: {
    bloques: 7,
    precio: "$0/mes",
    permitidos: [
      "precios",
      "tipo_cambio",
      "clima",
      "situacion",
      "consejo",
      "muestra_trial",
      "plan_info",
    ],
    prohibidos: [
      "insights_pro",
      "escenarios_pro",
      "termometro_pro",
      "alertas_pro",
      "finanzas",
      "hacienda",
      "oportunidad_venta",
      "riesgos_operativos",
      "radar_web_pro_completo",
    ],
  },
  basico: {
    bloques: 9,
    precio: "$9.000/mes",
    permitidos: [
      "precios",
      "tipo_cambio",
      "clima",
      "situacion",
      "consejo",
      "oportunidad_venta",
      "riesgos_operativos",
      "noticias",
      "plan_info",
    ],
    prohibidos: [
      "insights_pro",
      "escenarios_pro",
      "termometro_pro",
      "alertas_pro",
      "radar_web_pro_completo",
    ],
  },
  pro: {
    bloques: 13,
    precio: "$18.000/mes",
    permitidos: [
      "precios",
      "tipo_cambio",
      "clima",
      "situacion",
      "consejo",
      "oportunidad_venta",
      "riesgos_operativos",
      "noticias",
      "finanzas",
      "hacienda",
      "insights_pro",
      "escenarios_pro",
      "termometro_pro",
      "alertas_pro",
      "radar_web_pro_completo",
      "plan_info",
    ],
    prohibidos: [],
  },
};

module.exports = {
  PLAN_SCHEMA,
};
