module.exports = {
  whatsappUsuario: [
    { comando: "MI PLAN", descripcion: "Muestra tu plan actual." },
    { comando: "QUIERO PLAN GRATIS | BASICO | PRO", descripcion: "Cambia tu plan." },
    { comando: "QUIERO DESUSCRIBIRME", descripcion: "Cancela suscripción en Mercado Pago y te pasa a Plan Gratis." },
    { comando: "MI NOMBRE <nombre>", descripcion: "Actualiza tu nombre." },
    { comando: "MI EMAIL <correo>", descripcion: "Actualiza tu email para pagos/suscripciones." },
    { comando: "MI ZONA <provincia>, <partido>", descripcion: "Actualiza tu ubicación productiva." },
    { comando: "MIS CULTIVOS <c1, c2, ...>", descripcion: "Actualiza tus cultivos activos." },
    { comando: "MI GANADO <cat1, cat2, ...>", descripcion: "Actualiza categorías ganaderas." },
    { comando: "MI PERFIL MIXTO", descripcion: "Configura perfil mixto (cultivos + ganadería)." },
    { comando: "VER MI PERFIL", descripcion: "Muestra tus datos actuales guardados." },
    { comando: "MI RESUMEN", descripcion: "Inicia el resumen interactivo por pasos (mercado, dato clave, clima)." },
    { comando: "MIS ALERTAS", descripcion: "Lista tus alertas activas." },
    { comando: "ALERTA ... / AVISAME ...", descripcion: "Crea una alerta de precio." },
    { comando: "CANCELAR ALERTA <id>", descripcion: "Cancela una alerta puntual." },
    { comando: "MIS GASTOS", descripcion: "Resumen de gastos (Plan Pro)." },
    { comando: "MIS VENTAS", descripcion: "Resumen de ventas (Plan Pro)." },
    { comando: "MI MARGEN", descripcion: "Resumen de margen (Plan Pro)." },
    { comando: "COMPLETAR PERFIL", descripcion: "Abre flujo de perfil extendido." },
    { comando: "MIS NOTICIAS <cantidad>", descripcion: "En Plan Pro, define cuántas noticias querés ver (1-15)." },
    { comando: "FLETE <origen> A <destino>", descripcion: "Calcula flete estimado por km y gasoil actual." },
    { comando: "VER COMANDO", descripcion: "Muestra todos los comandos y su explicación." },
    { comando: "BORRAR MIS DATOS", descripcion: "Pedís borrar tu cuenta; luego confirmás con SI BORRO MIS DATOS." },
    { comando: "Cualquier consulta libre", descripcion: "Respuesta IA con contexto agro." },
  ],
  whatsappAdmin: [
    { comando: "ESTADO", descripcion: "Estado general del sistema." },
    { comando: "ESTADO SISTEMA", descripcion: "Estado detallado (DB, IA, usuarios)." },
    { comando: "ESTADO IA", descripcion: "Orden de fallback de IA." },
    { comando: "ESTADO DB", descripcion: "Chequeo rápido de base de datos." },
    { comando: "USUARIOS", descripcion: "Resumen de usuarios y últimos registros." },
    { comando: "FUENTES", descripcion: "Resumen de estado de fuentes activas." },
  ],
  apiAdmin: [
    { metodo: "GET", endpoint: "/api/dashboard/admin/agent-runtime?dias=7", descripcion: "Flags/límites del agente + mix ia_provider (días 1–90)." },
    { metodo: "GET", endpoint: "/api/dashboard/admin/agent-env", descripcion: "Definiciones y valores editables del agente (.env permitido, sin secretos)." },
    { metodo: "POST", endpoint: "/api/dashboard/admin/agent-env", descripcion: "Actualiza claves permitidas en .env y reinicia PM2 si está disponible." },
    { metodo: "GET", endpoint: "/api/dashboard/admin/usuarios", descripcion: "Listado de usuarios admin." },
    { metodo: "GET", endpoint: "/api/dashboard/admin/usuario-detalle", descripcion: "Detalle completo por usuario." },
    { metodo: "GET", endpoint: "/api/dashboard/admin/pendientes", descripcion: "Pendientes de onboarding." },
    { metodo: "POST", endpoint: "/api/dashboard/admin/usuario-accion", descripcion: "Activar/Pausar/Eliminar usuario." },
    { metodo: "POST", endpoint: "/api/dashboard/admin/alerta-accion", descripcion: "Reactivar/Cancelar alerta." },
    { metodo: "POST", endpoint: "/api/dashboard/admin/pendiente-accion", descripcion: "Acciones sobre pendientes." },
    { metodo: "POST", endpoint: "/api/dashboard/admin/envio-masivo", descripcion: "Encola envío masivo WhatsApp; responde 202 + jobId." },
    { metodo: "GET", endpoint: "/api/dashboard/admin/envio-masivo/estado?jobId=", descripcion: "Estado del envío masivo (running|listo|error)." },
    { metodo: "GET", endpoint: "/api/dashboard/admin/whatsapp-qr.png", descripcion: "PNG del QR de vinculación WhatsApp (si existe)." },
    { metodo: "POST", endpoint: "/api/admin/recolectar", descripcion: "Ejecuta recolector manual." },
    {
      metodo: "POST",
      endpoint: "/api/admin/enviar-resumen",
      descripcion:
        "Invitación resumen interactivo (como el cron). Body: whatsapp | usuario_id | usuario_ids[].",
    },
  ],
};
