module.exports = {
  granos: {
    disponible: [
      {
        id: "magyp_precios_php",
        nombre: "MAGyP - Cotizaciones granos (precios.php)",
        url: "https://www.magyp.gob.ar/mercadosagropecuarios/precios.php",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo", "cebada"],
        plaza: "nacional",
        region: "todas",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/granos_magyp_precios_php.js",
        prioridad: "alta",
        orden_ingesta: 2,
      },
      {
        id: "maroun_pizarra",
        nombre: "MAROUN S.A. - Pizarra granos (Bahía Blanca)",
        url: "https://www.maroun.com.ar/",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo", "cebada"],
        plaza: "bahia_blanca",
        region: "pampeana",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/granos_maroun_pizarra.js",
        prioridad: "media",
        orden_ingesta: 4,
      },
      {
        id: "cac_bcr",
        nombre: "Cámara Arbitral de Cereales - BCR",
        url: "https://www.cac.bcr.com.ar/es/precios-de-pizarra",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo", "cebada"],
        plaza: "rosario",
        region: "pampeana",
        frecuencia: "diaria",
        horario: "10:00",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/granos_cac.js",
        prioridad: "alta",
        metodo_preferido: "scraping_html_tablas",
        orden_ingesta: 2,
      },
      {
        id: "magyp_fob",
        nombre: "Ministerio de Agricultura - Precios FOB",
        url: "https://www.magyp.gob.ar/sitio/areas/ss_mercados_agropecuarios/fob_oficiales/_archivos/000021_Precios%20Fob%20Api.php",
        tipo: "api_json",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo"],
        plaza: "nacional",
        region: "todas",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/granos_magyp_fob.js",
      },
      {
        id: "afa_scl",
        nombre: "AFA San Cristóbal - Mercados en línea",
        url: "https://www.afascl.coop/afadiario/mercados-en-linea",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo", "girasol"],
        plaza: "san_cristobal",
        region: "pampeana",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/granos_afa.js",
      },
      {
        id: "sio_granos",
        nombre: "SIO Granos - Operaciones reales",
        url: "https://monitorsiogranos.magyp.gob.ar/monitorsiogranos.html",
        tipo: "api_json",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo"],
        plaza: "nacional",
        region: "argentina",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/siogranos.js",
        prioridad: "media",
        metodo_preferido: "api_json_para_validacion",
        orden_ingesta: 3,
        nota: "Uso recomendado para validar precios y detectar desvíos.",
      },
    ],
    futuros: [
      {
        id: "matba_rofex",
        nombre: "MATba-Rofex - Futuros agropecuarios",
        url: "https://api.matbarofex.com.ar/v2/symbol",
        tipo: "api_json",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo", "cebada"],
        region: "nacional",
        frecuencia: "diaria",
        oficial: true,
        activa: false,
        scraper: "src/scrapers/futuros_matba.js",
        nota: "Requiere autenticación/token (actualmente HTTP 401 en verificación básica).",
        prioridad: "critica",
        metodo_preferido: "api_json_con_fallback_scraping",
        orden_ingesta: 1,
      },
      {
        id: "cbot_chicago",
        nombre: "CBOT Chicago - Futuros internacionales",
        url: "https://www.afascl.coop/afadiario/mercados-en-linea",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo"],
        region: "internacional",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/granos_afa.js",
      },
    ],
  },

  ganaderia: {
    vacunos: [
      {
        id: "liniers",
        nombre: "Mercado Agroganadero (ex Liniers)",
        url: "http://www.mercadoagroganadero.com.ar/dll/inicio.dll",
        tipo: "scraping_html",
        productos: ["novillo", "vaca", "ternero", "vaquillonas", "toros"],
        plaza: "canuelas",
        region: "nacional",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/hacienda.js",
        prioridad: "alta",
        metodo_preferido: "scraping_html",
        orden_ingesta: 1,
      },
      {
        id: "mercadodeliniers_web",
        nombre: "Mercado de Liniers (fallback web)",
        url: "https://www.mercadodeliniers.com.ar",
        tipo: "scraping_html",
        productos: ["novillo", "vaca", "ternero", "vaquillona", "toro"],
        plaza: "canuelas",
        region: "nacional",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/hacienda.js",
        nota: "Fuente secundaria/fallback cuando falla mercadoagroganadero.com.ar.",
      },
      {
        id: "rosgan_remates",
        nombre: "Rosgan - Resultados de remates",
        url: "https://www.rosgan.com.ar/",
        tipo: "scraping_html",
        productos: ["ternero", "invernada"],
        plaza: "nacional",
        region: "argentina",
        frecuencia: "semanal",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/rosgan.js",
        prioridad: "critica",
        metodo_preferido: "extractor_estructurado_tablas",
        orden_ingesta: 2,
        nota: "Extractor estructurado para alimentar tendencia ganadera (suba/baja/estable).",
      },
      {
        id: "campos_y_ganados",
        nombre: "Campos y Ganados - Remates",
        url: "https://www.camposyganados.com/",
        tipo: "scraping_pdf",
        productos: ["ternero", "invernada", "novillo", "vaca"],
        plaza: "nacional",
        region: "argentina",
        frecuencia: "semanal",
        oficial: false,
        activa: false,
        scraper: null,
        prioridad: "alta",
        metodo_preferido: "scraping_links_y_parsing_pdf",
        orden_ingesta: 3,
        nota: "Requiere extracción de PDFs y parsing por regex/fallback.",
      },
      {
        id: "ruralnet_ganaderia",
        nombre: "Ruralnet - Tendencias ganaderas",
        url: "https://ruralnet.com.ar/",
        tipo: "scraping_html",
        productos: ["tendencias_hacienda", "referencias_precio"],
        plaza: "nacional",
        region: "argentina",
        frecuencia: "diaria",
        oficial: false,
        activa: false,
        scraper: null,
        prioridad: "media",
        metodo_preferido: "scraping_articulos",
        orden_ingesta: 4,
        nota: "Uso como fallback de tendencia cuando faltan precios duros.",
      },
    ],
    porcinos: [
      {
        id: "siocarnes_porcino",
        nombre: "SIO Carnes - Porcino",
        url: "https://siocarnes.magyp.gob.ar/MonitorSioCarnes/MonitorSioCarnes?idAnimal=2&animal=PORCINO#",
        tipo: "scraping_html",
        productos: ["porcino_referencia"],
        region: "argentina",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/magyp_extra.js",
      },
      {
        id: "rosporc_bcr",
        nombre: "Rosporc BCR",
        url: "https://www.rosporc.com/",
        tipo: "scraping_html",
        productos: ["cerdo_capon", "precio_referencia"],
        region: "nacional",
        frecuencia: "semanal",
        oficial: false,
        activa: false,
        scraper: null,
      },
      {
        id: "tres_tres_ar",
        nombre: "3tres3 Argentina",
        url: "https://www.3tres3.com/ar/",
        tipo: "scraping_html",
        productos: ["porcinos_mercado"],
        region: "argentina",
        frecuencia: "semanal",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
    avicultura: [
      {
        id: "magyp_avicultura_ref",
        nombre: "MAGYP Avicultura (referencial)",
        url: "https://www.magyp.gob.ar/",
        tipo: "por_investigar",
        productos: ["pollo_vivo", "huevo_docena"],
        region: "argentina",
        frecuencia: "semanal",
        oficial: true,
        activa: false,
        scraper: null,
      },
    ],
    ovinos: [
      {
        id: "ovinos_portal",
        nombre: "Ovinos Argentina",
        url: "https://ovinos.com.ar/",
        tipo: "scraping_html",
        productos: ["cordero", "oveja", "lana"],
        region: "argentina",
        frecuencia: "semanal",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
    lacteos: [
      {
        id: "ocla",
        nombre: "OCLA",
        url: "https://www.ocla.org.ar/",
        tipo: "scraping_html",
        productos: ["leche_cruda_litro", "lacteos_indicadores"],
        region: "argentina",
        frecuencia: "mensual",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
  },

  frutas_verduras: {
    mercado_central: [
      {
        id: "mercado_central_ba",
        nombre: "Mercado Central de Buenos Aires",
        url: "https://www.mercadocentral.gob.ar/joom/index.php/precios-diarios",
        tipo: "por_investigar",
        productos: ["todas_frutas", "todas_verduras"],
        plaza: "buenos_aires",
        region: "nacional",
        frecuencia: "diaria",
        oficial: true,
        activa: false,
        scraper: null,
        nota: "URL actual devuelve 404. Pendiente URL vigente/estructura.",
        prioridad: "alta",
        metodo_preferido: "scraping_html_tablas",
        orden_ingesta: 1,
      },
      {
        id: "precios_del_central",
        nombre: "Precios del Central",
        url: "https://www.preciosdelcentral.com.ar/",
        tipo: "scraping_html",
        productos: ["frutas", "verduras"],
        plaza: "buenos_aires",
        region: "nacional",
        frecuencia: "diaria",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
  },

  economias_regionales: {
    yerba_mate: [
      {
        id: "inym",
        nombre: "Instituto Nacional de la Yerba Mate",
        url: "https://www.inym.org.ar/estadisticas/precio-de-la-hoja-verde/",
        tipo: "por_investigar",
        productos: ["yerba_mate_hoja_verde"],
        region: "nea_misiones",
        frecuencia: "mensual",
        oficial: true,
        activa: false,
        scraper: null,
        nota: "URL actual devuelve 404. Pendiente sección vigente.",
      },
    ],
    "caña_azucar": [],
    citrus: [],
    miel: [
      {
        id: "magyp_monitor_miel",
        nombre: "MAGYP Monitor SIM Miel",
        url: "https://www.magyp.gob.ar/monitorpreciosmiel/",
        tipo: "scraping_html",
        productos: ["miel_referencia"],
        region: "argentina",
        frecuencia: "semanal",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/magyp_extra.js",
      },
    ],
    vitivinicultura: [
      {
        id: "inv_ar",
        nombre: "Instituto Nacional de Vitivinicultura",
        url: "https://www.argentina.gob.ar/inv",
        tipo: "scraping_html",
        productos: ["uva", "vino_granel"],
        region: "cuyo",
        frecuencia: "semanal",
        oficial: true,
        activa: false,
        scraper: null,
      },
    ],
    frutales_patagonicos: [],
    tabaco: [],
  },

  hortalizas: {
    papa: [
      {
        id: "mcba_oficial_papa",
        nombre: "MCBA Oficial - Papa (precios + ingresos)",
        url: "https://www.mcba.gob.ar/precios-de-referencia",
        tipo: "scraping_html",
        productos: ["papa"],
        region: "buenos_aires",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/papa_mcba.js",
        prioridad: "critica",
        metodo_preferido: "scraping_html_tablas",
        orden_ingesta: 1,
        nota: "Fuente prioritaria para papa. Intentar extraer precio y volumen/ingresos diarios.",
      },
      {
        id: "mcba_oficial_ingresos",
        nombre: "MCBA Oficial - Ingresos",
        url: "https://www.mcba.gob.ar/ingresos",
        tipo: "scraping_html",
        productos: ["papa", "ingresos_mercado"],
        region: "buenos_aires",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/papa_mcba.js",
      },
      {
        id: "argenpapa_mcba",
        nombre: "Argenpapa - Cotizaciones Mercado Central BA",
        url: "https://www.argenpapa.com.ar/mercados/",
        tipo: "scraping_html",
        productos: ["papa"],
        region: "buenos_aires",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/papa_argenpapa.js",
        orden_ingesta: 2,
        nota: "Fallback operativo con buen detalle sectorial cuando MCBA oficial no publica en formato parseable.",
      },
      {
        id: "magyp_fyh_mcba_csv",
        nombre: "MAGyP/Datos.gob.ar - FYH Mercado Central (CSV)",
        url: "https://datos.magyp.gob.ar/dataset/8b4d6a1f-753d-4707-9085-bdcbbc47f00b/resource/6dce1e87-7988-4eaf-b0e1-b3abbb3964da/download/precios-fyh-mercadocentral-bsas-arg-2017-2c2018-.csv",
        tipo: "csv",
        productos: ["papa"],
        region: "buenos_aires",
        frecuencia: "historica",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/papa_magyp_csv.js",
        nota: "Fuente de respaldo (serie histórica; baja frecuencia de actualización).",
      },
    ],
  },

  economia_macro: {
    tipo_cambio: [
      {
        id: "dolarapi",
        nombre: "DolarAPI",
        url: "https://dolarapi.com/v1/dolares",
        tipo: "api_json",
        productos: ["oficial", "blue", "mep", "ccl"],
        frecuencia: "tiempo_real",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/dolar.js",
        prioridad: "critica",
        metodo_preferido: "api_json",
        orden_ingesta: 1,
      },
      {
        id: "bluelytics",
        nombre: "Bluelytics",
        url: "https://api.bluelytics.com.ar/v2/latest",
        tipo: "api_json",
        productos: ["oficial", "blue"],
        frecuencia: "tiempo_real",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/dolar.js",
        nota: "Fuente secundaria/fallback cuando falla DolarAPI.",
      },
      {
        id: "argentinadatos_tc",
        nombre: "ArgentinaDatos",
        url: "https://www.argentinadatos.com/",
        tipo: "api_json",
        productos: ["dolar_oficial", "dolar_blue", "dolar_mep", "dolar_ccl"],
        frecuencia: "tiempo_real",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
    combustibles: [
      {
        id: "ypf_gasoil",
        nombre: "YPF - Precio gasoil por provincia",
        url: "https://www.ypf.com/precios",
        tipo: "por_investigar",
        productos: ["gasoil_grado2", "gasoil_grado3"],
        frecuencia: "semanal",
        oficial: true,
        activa: false,
        scraper: null,
      },
      {
        id: "surtidores_gasoil",
        nombre: "Surtidores",
        url: "https://www.surtidores.com.ar/",
        tipo: "scraping_html",
        productos: ["gasoil_grado2", "gasoil_grado3"],
        frecuencia: "semanal",
        oficial: false,
        activa: false,
        scraper: null,
      },
      {
        id: "fadeeac_tarifas",
        nombre: "FADEEAC",
        url: "https://www.fadeeac.org.ar/",
        tipo: "scraping_html",
        productos: ["flete_granario_km", "flete_referencia"],
        frecuencia: "semanal",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
  },

  clima: [
    {
      id: "open_meteo",
      nombre: "Open-Meteo",
      url: "https://api.open-meteo.com/v1/forecast",
      tipo: "api_json",
      cobertura: "mundial",
      variables: ["temperatura", "precipitacion", "helada", "viento"],
      frecuencia: "tiempo_real",
      oficial: true,
      activa: true,
      scraper: "src/scrapers/clima.js",
    },
    {
      id: "smn",
      nombre: "Servicio Meteorológico Nacional",
      url: "https://www.smn.gob.ar",
      tipo: "por_investigar",
      cobertura: "argentina",
      frecuencia: "diaria",
      oficial: true,
      activa: false,
      scraper: null,
      nota: "Para alertas oficiales de helada y granizo",
    },
  ],

  insumos: {
    mercado_online: [
      {
        id: "agrofy_insumos",
        nombre: "Agrofy Insumos",
        url: "https://www.agrofy.com.ar/insumos",
        tipo: "scraping_html",
        productos: ["insumos_varios"],
        region: "nacional",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/insumos.js",
      },
      {
        id: "agrofy_proxy_jina",
        nombre: "Agrofy Insumos (proxy jina.ai)",
        url: "https://r.jina.ai/http://www.agrofy.com.ar/insumos/productos-con-precio",
        tipo: "scraping_html",
        productos: ["insumos_varios"],
        region: "nacional",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/insumos.js",
        nota: "Fallback técnico ante bloqueos 403 del sitio principal.",
      },
      {
        id: "agroads_insumos",
        nombre: "Agroads Insumos",
        url: "https://www.agroads.com.ar/insumos-agricolas",
        tipo: "scraping_html",
        productos: ["insumos_varios"],
        region: "nacional",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/insumos.js",
      },
      {
        id: "agroads_proxy_jina",
        nombre: "Agroads Insumos (proxy jina.ai)",
        url: "https://r.jina.ai/http://www.agroads.com.ar/insumos-agricolas",
        tipo: "scraping_html",
        productos: ["insumos_varios"],
        region: "nacional",
        frecuencia: "diaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/insumos.js",
        nota: "Fallback técnico ante bloqueos del sitio principal.",
      },
    ],
  },

  noticias_agro: {
    portales: [
      {
        id: "magyp_estimaciones_monitor",
        nombre: "MAGYP Estimaciones - Monitor",
        url: "https://www.magyp.gob.ar/sitio/areas/estimaciones/monitor/",
        tipo: "scraping_html",
        productos: ["estimaciones_agricolas"],
        region: "argentina",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/magyp_extra.js",
      },
      {
        id: "noticiasdecampo_wp",
        nombre: "Noticias de Campo (WordPress API)",
        url: "https://www.noticiasdecampo.com/wp-json/wp/v2/posts",
        tipo: "api_json",
        productos: ["noticias_agro"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/noticias_web.js",
      },
      {
        id: "infocampo_wp",
        nombre: "InfoCampo (WordPress API)",
        url: "https://www.infocampo.com.ar/wp-json/wp/v2/posts",
        tipo: "api_json",
        productos: ["noticias_agro"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/noticias_web.js",
      },
      {
        id: "infocampo_ultimas_web",
        nombre: "InfoCampo - Últimas noticias (web)",
        url: "https://www.infocampo.com.ar/ultimas-noticias/",
        tipo: "scraping_html",
        productos: ["noticias_agro"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/noticias_web.js",
        nota: "Referencia editorial adicional; la ingesta principal usa WordPress API.",
      },
      {
        id: "infocampo_mercados_empresas",
        nombre: "InfoCampo - Mercados y empresas (web)",
        url: "https://www.infocampo.com.ar/category/mercados-y-empresas/",
        tipo: "scraping_html",
        productos: ["noticias_agro", "mercados"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/noticias_web.js",
        nota: "Referencia de mercado para complementar notas de portada.",
      },
      {
        id: "todoagro_web",
        nombre: "TodoAgro (portada web)",
        url: "https://www.todoagro.com.ar",
        tipo: "scraping_html",
        productos: ["noticias_agro", "mercados"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/noticias_web.js",
      },
      {
        id: "lncampo_mercado_granos",
        nombre: "LN Campo - Mercado de granos",
        url: "https://www.lncampo.lanacion.com.ar/mercado-granos/",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo", "girasol", "sorgo"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/mercados_web.js",
      },
      {
        id: "monitor_comercio_granario",
        nombre: "MAGYP Monitor Comercio Granario",
        url: "https://monitorssma.magyp.gob.ar/siogranos.dashboardgranos.aspx",
        tipo: "scraping_html",
        productos: ["soja", "maiz", "trigo", "cebada", "sorgo"],
        region: "argentina",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/magyp_extra.js",
      },
      {
        id: "lanacion_campo",
        nombre: "La Nación Campo - Economía/Campo",
        url: "https://www.lanacion.com.ar/economia/campo/",
        tipo: "scraping_html",
        productos: ["noticias_agro"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: true,
        scraper: "src/scrapers/noticias_web.js",
        nota: "Fuente complementaria/no crítica: si falla, no degrada el pipeline de noticias.",
      },
      {
        id: "inta_contexto_papa",
        nombre: "INTA - Contexto técnico papa/horticultura",
        url: "https://www.argentina.gob.ar/inta",
        tipo: "scraping_html",
        productos: ["noticias_agro", "papa", "horticultura"],
        region: "argentina",
        frecuencia: "diaria",
        oficial: true,
        activa: true,
        scraper: "src/scrapers/inta_contexto.js",
        nota: "Fuente técnica complementaria para contexto sectorial y manejo en papa.",
      },
      {
        id: "todoagro_rss",
        nombre: "TodoAgro RSS",
        url: "https://www.todoagro.com.ar/feed/",
        tipo: "rss",
        productos: ["noticias_agro", "ganaderia", "mercados"],
        region: "argentina",
        frecuencia: "horaria",
        oficial: false,
        activa: false,
        scraper: null,
      },
    ],
  },

  regulatorio: {
    oficial: [
      {
        id: "senasa",
        nombre: "SENASA",
        url: "https://www.senasa.gob.ar/",
        tipo: "manual_web",
        productos: ["sanidad_animal", "resoluciones_sanitarias"],
        region: "argentina",
        frecuencia: "manual",
        oficial: true,
        activa: false,
        scraper: null,
      },
      {
        id: "boletin_oficial",
        nombre: "Boletín Oficial",
        url: "https://www.boletinoficial.gob.ar/",
        tipo: "manual_web",
        productos: ["retenciones", "normativa_agro"],
        region: "argentina",
        frecuencia: "manual",
        oficial: true,
        activa: false,
        scraper: null,
      },
    ],
  },
};
